import Head from 'next/head'
import NavBar from '../components/NavBar/NavBar'
import {cakes} from "./api/helpers/cake-list";
import {CakePageProps} from "../types/types";
import CakeList from "../components/cakeslist";


const CakesPostcards = ({cakes}: CakePageProps) => (
    <>
        <Head>
            <title>Торты открытки</title>
            <meta name='description' content='Generated by create next app'/>
        </Head>

        <NavBar current={'cake-postcards'} showLogo={true}/>

        <div className='container'>
            <h1>ТОРТЫ ОТКРЫТКИ</h1>
            <section>
                <CakeList cakes={cakes}/>
            </section>
        </div>
    </>
)

CakesPostcards.getInitialProps = async () => {

    return {cakes: cakes.filter(cake => cake.section===2)}
}

export default CakesPostcards